### ISSUE TITLE
No module named "dotenv"

### ISSUE THREAD

**Issue by Nadineli** [cocktailpeanut/rvc.pinokio#1]
Hi, 

on Windows 11, when trying to launch RVC, i get the following error:

ModuleNotFoundError: No module named "dotenv"

**Comment by jaylex32** [comment]
mac m1 chip ventura wont convert anything.
log:
/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
2023-11-04 10:43:07 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 500 Internal Server Error"
2023-11-04 10:43:07 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-04 10:44:47 | INFO | infer.modules.vc.modules | Get sid: 21Savage.pth
2023-11-04 10:44:47 | INFO | infer.modules.vc.modules | Loading: assets/weights/21Savage.pth
2023-11-04 10:44:47 | INFO | infer.modules.vc.modules | Select index: logs/21Savage/added_IVF1310_Flat_nprobe_8.index
2023-11-04 10:44:47 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK"
2023-11-04 10:44:47 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
2023-11-04 10:45:01 | INFO | infer.modules.vc.pipeline | Loading rmvpe model,assets/rmvpe/rmvpe.pt
2023-11-04 10:45:01 | WARNING | infer.modules.vc.modules | Traceback (most recent call last):
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/modules/vc/modules.py", line 185, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/modules/vc/pipeline.py", line 354, in pipeline
    pitch, pitchf = self.get_f0(
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/modules/vc/pipeline.py", line 149, in get_f0
    self.model_rmvpe = RMVPE(
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/lib/rmvpe.py", line 563, in __init__
    self.model = get_default_model()
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/lib/rmvpe.py", line 544, in get_default_model
    ckpt = torch.load(model_path, map_location="cpu")
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/torch/serialization.py", line 996, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'assets/rmvpe/rmvpe.pt'

Traceback (most recent call last):
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
2023-11-04 10:45:01 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 500 Internal Server Error"
2023-11-04 10:45:01 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"

thanks in advance

**Comment by 6Morpheus6** [comment]
> mac m1 chip ventura wont convert anything. log: /pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict output = await app.get_blocks().process_api( File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1349, in process_api data = self.postprocess_data(fn_index, result["prediction"], state) File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1283, in postprocess_data prediction_value = block.postprocess(prediction_value) File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 2586, in postprocess file_path = self.audio_to_temp_file( File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 360, in audio_to_temp_file temp_dir = Path(dir) / self.hash_bytes(data.tobytes()) AttributeError: 'NoneType' object has no attribute 'tobytes' 2023-11-04 10:43:07 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 500 Internal Server Error" 2023-11-04 10:43:07 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK" 2023-11-04 10:44:44 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK" 2023-11-04 10:44:47 | INFO | infer.modules.vc.modules | Get sid: 21Savage.pth 2023-11-04 10:44:47 | INFO | infer.modules.vc.modules | Loading: assets/weights/21Savage.pth 2023-11-04 10:44:47 | INFO | infer.modules.vc.modules | Select index: logs/21Savage/added_IVF1310_Flat_nprobe_8.index 2023-11-04 10:44:47 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 200 OK" 2023-11-04 10:44:47 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK" 2023-11-04 10:45:01 | INFO | infer.modules.vc.pipeline | Loading rmvpe model,assets/rmvpe/rmvpe.pt 2023-11-04 10:45:01 | WARNING | infer.modules.vc.modules | Traceback (most recent call last): File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/modules/vc/modules.py", line 185, in vc_single audio_opt = self.pipeline.pipeline( File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/modules/vc/pipeline.py", line 354, in pipeline pitch, pitchf = self.get_f0( File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/modules/vc/pipeline.py", line 149, in get_f0 self.model_rmvpe = RMVPE( File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/lib/rmvpe.py", line 563, in **init** self.model = get_default_model() File "/Users/javier/pinokio/api/rvc.pinokio.git/app/infer/lib/rmvpe.py", line 544, in get_default_model ckpt = torch.load(model_path, map_location="cpu") File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/torch/serialization.py", line 996, in load with _open_file_like(f, 'rb') as opened_file: File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like return _open_file(name_or_buffer, mode) File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/torch/serialization.py", line 426, in **init** super().**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'assets/rmvpe/rmvpe.pt'
> 
> Traceback (most recent call last): File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict output = await app.get_blocks().process_api( File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1349, in process_api data = self.postprocess_data(fn_index, result["prediction"], state) File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1283, in postprocess_data prediction_value = block.postprocess(prediction_value) File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 2586, in postprocess file_path = self.audio_to_temp_file( File "/Users/javier/pinokio/api/rvc.pinokio.git/app/env/lib/python3.10/site-packages/gradio/components.py", line 360, in audio_to_temp_file temp_dir = Path(dir) / self.hash_bytes(data.tobytes()) AttributeError: 'NoneType' object has no attribute 'tobytes' 2023-11-04 10:45:01 | INFO | httpx | HTTP Request: POST http://localhost:7865/api/predict "HTTP/1.1 500 Internal Server Error" 2023-11-04 10:45:01 | INFO | httpx | HTTP Request: POST http://localhost:7865/reset "HTTP/1.1 200 OK"
> 
> thanks in advance

rmvpe.pt can be found on huggingface.
Put it into the folder ./pinokio/rvc.pinokio.git/app/assets/rmvpe

https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main

**Comment by DoubleHelixX** [comment]
Any updates on the 'ModuleNotFoundError: No module named "dotenv"' error ??? It has been almost a year by now & I currently have this issue as well.

@Nadineli Any updates on fixes you discovered?

**Comment by 6Morpheus6** [comment]
> Any updates on the 'ModuleNotFoundError: No module named "dotenv"' error ??? It has been almost a year by now & I currently have this issue as well.
> 
> @Nadineli Any updates on fixes you discovered?
@DoubleHelixX On windows you can try this:
- Open Anaconda Powershell
- Navigate to the rvc folder `cd .\pinokio\api\rvc.pinokio.git\app`.
 - Let's assume your pinokio home directory is `C:\pinokio`  
 the full command would be `cd C:\pinokio\api\rvc.pinokio.git\app`
- Activate the rvc environment `env\Scripts\activate`  
You should see a green (env) in front of your prompt now. Please don't proceed if the (env) is missing.
- Install the requirements with the pep517 flag `pip install -r requirements.txt --use-pep517`
- If the requirements got installed without error, start pinokio and run rvc

**Comment by phoxoey** [comment]
Had the same issue, not only with RVC but also other application via Pinokio. Only solution that worked was to 

- Completely remove all Microsoft Visual Studio applications which included Microsoft Build tools. Once all is removed
-  Try to download FaceFusion via Pinokio. Even if you already have it installed, just click download. This will popup a window that tells you everything you need to install and you will see VS as 'not installed'.
- Continue with the download and pinokio will download Visual Studio for you. After that install, you don't have to continue with the downloading of FaceFusion if you already have it.
- Now try to install RVC.
